export const inventoryList = [
  {
    categoryName: "Electronics",
    categoryId: 1,
    items: [
      {
        itemId: "101",
        itemName: "Laptop",
        quantity: 15,
        pricePerUnit: 899.99,
        supplier: "TechSupply Co.",
        lastRestockDate: "2024-08-25",
        location: "Aisle 3, Shelf B",
      },
      {
        itemId: "103",
        itemName: "Wireless Mouse",
        quantity: 30,
        pricePerUnit: 24.99,
        supplier: "GadgetsPlus",
        lastRestockDate: "2024-08-30",
        location: "Aisle 2, Shelf F",
      },
      {
        itemId: "106",
        itemName: "Smartphone",
        quantity: 20,
        pricePerUnit: 699.99,
        supplier: "MobileTech Inc.",
        lastRestockDate: "2024-09-05",
        location: "Aisle 3, Shelf A",
      },
      {
        itemId: "107",
        itemName: "Tablet",
        quantity: 10,
        pricePerUnit: 499.99,
        supplier: "TechSupply Co.",
        lastRestockDate: "2024-09-02",
        location: "Aisle 3, Shelf C",
      },
    ],
  },
  {
    categoryName: "furniture",
    categoryId: 2,
    items: [
      {
        itemId: "102",
        itemName: "Office Chair",
        quantity: 8,
        pricePerUnit: 199.99,
        supplier: "OfficeWorld",
        lastRestockDate: "2024-09-01",
        location: "Aisle 7, Shelf D",
      },
      {
        itemId: "108",
        itemName: "Standing Desk",
        quantity: 5,
        pricePerUnit: 399.99,
        supplier: "FurnitureHub",
        lastRestockDate: "2024-09-04",
        location: "Aisle 7, Shelf A",
      },
      {
        itemId: "109",
        itemName: "Bookshelf",
        quantity: 7,
        pricePerUnit: 149.99,
        supplier: "HomeEssentials",
        lastRestockDate: "2024-08-29",
        location: "Aisle 7, Shelf B",
      },
      {
        itemId: "110",
        itemName: "Conference Table",
        quantity: 2,
        pricePerUnit: 799.99,
        supplier: "OfficeWorld",
        lastRestockDate: "2024-08-31",
        location: "Aisle 8, Shelf C",
      },
    ],
  },
  {
    categoryName: "lighting",
    categoryId: 3,
    items: [
      {
        itemId: "104",
        itemName: "Desk Lamp",
        quantity: 12,
        pricePerUnit: 49.99,
        supplier: "HomeEssentials",
        lastRestockDate: "2024-08-28",
        location: "Aisle 5, Shelf A",
      },
      {
        itemId: "111",
        itemName: "Floor Lamp",
        quantity: 10,
        pricePerUnit: 89.99,
        supplier: "BrightLights",
        lastRestockDate: "2024-08-30",
        location: "Aisle 5, Shelf B",
      },
      {
        itemId: "112",
        itemName: "Pendant Light",
        quantity: 6,
        pricePerUnit: 119.99,
        supplier: "LightingPlus",
        lastRestockDate: "2024-08-27",
        location: "Aisle 5, Shelf C",
      },
      {
        itemId: "113",
        itemName: "Ceiling Fan with Light",
        quantity: 4,
        pricePerUnit: 149.99,
        supplier: "FanWorks",
        lastRestockDate: "2024-08-26",
        location: "Aisle 5, Shelf D",
      },
    ],
  },
  {
    categoryName: "stationery",
    categoryId: 4,
    items: [
      {
        itemId: "105",
        itemName: "Notebook",
        quantity: 50,
        pricePerUnit: 3.49,
        supplier: "PaperGoods Inc.",
        lastRestockDate: "2024-09-03",
        location: "Aisle 1, Shelf C",
      },
      {
        itemId: "114",
        itemName: "Pen Pack (12 pcs)",
        quantity: 100,
        pricePerUnit: 5.99,
        supplier: "StationeryWorld",
        lastRestockDate: "2024-09-04",
        location: "Aisle 1, Shelf B",
      },
      {
        itemId: "115",
        itemName: "Stapler",
        quantity: 40,
        pricePerUnit: 7.99,
        supplier: "OfficeSupplies Co.",
        lastRestockDate: "2024-09-01",
        location: "Aisle 1, Shelf D",
      },
      {
        itemId: "116",
        itemName: "Highlighter Set",
        quantity: 60,
        pricePerUnit: 4.99,
        supplier: "ColorMark",
        lastRestockDate: "2024-09-02",
        location: "Aisle 1, Shelf A",
      },
    ],
  },
];
